# Generated by Django 5.2.7 on 2025-10-29 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='listProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_link', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
